bash scripts/tokenizer/train_vq.sh --cloud-save-path /tmp/ctap_tokenizer_16 \
--data-path /tmp/ctap_jpegs \
--image-size 256 \
--global-batch-size 128 \
--vq-model VQ-16 \
--use-encoder-patch \
--codebook-size 32768 \
--results-dir results_tokenizer_image_efficientnet_discfeature_16 \
--perceptual-weight 3.0 \
--reconstruction-weight 1.0 \
--disc-start 0 \
--compile \
--global-seed 42 \
--ssim-weight 0.0 \
--disc-feature-weight 1.0 \
--ckpt-every 2000 \